---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  roles_path: test/integration/roles
  attributes:
    openstack:
      release: icehouse
      developer_mode: true
    mysql:
      server_root_password: rootpass
      server_debian_password: debpass
      server_repl_password: replpass
      allow_remote_root: true
      root_network_acl:
        - "%"
    yum:
      epel:
        baseurl: "http://epel.osuosl.org/6/$basearch"
        enable: true
        gpgkey: "http://epel.osuosl.org/RPM-GPG-KEY-EPEL-6"
    authorization:
      sudo:
        users:
          - vagrant

platforms:
  - name: centos-6.6
    driver_config:
      attributes:
        mysql:
          version: 5.1
  - name: ubuntu-12.04
  - name: fedora-20

suites:
  - name: compute
    run_list:
      - role[openstack_ops_database]
      - role[openstack_controller]
      - role[openstack_compute]
      - recipe[openstack-mellanox::compute]
    excludes:
      - fedora-20
      - ubuntu-12.04
